import type {
  Operator, WasteRequest, Proposal, Collection, Destination, Notification, Certificate
} from './types';

export const OPERATORS: Operator[] = [
  {
    id: 'op1',
    name: 'Cooperativa Verde Vida',
    type: 'Cooperativa',
    specialties: ['Papel', 'Papelão', 'Plástico'],
    rating: 4.8,
    distance: 12,
    capacity: '2 toneladas/dia',
    services: ['Coleta', 'Triagem', 'Reciclagem'],
    serviceArea: 'Zona Norte e Leste de São Paulo',
    description: 'Cooperativa com 15 anos de experiência em materiais recicláveis secos. Equipe própria com veículos adaptados.',
    materialsAccepted: ['Papel', 'Papelão', 'Plástico PET', 'Plástico duro', 'Alumínio'],
  },
  {
    id: 'op2',
    name: 'Novo Ciclo Reciclagem',
    type: 'Recicladora',
    specialties: ['Plástico', 'Papelão', 'Metais'],
    rating: 4.6,
    distance: 8,
    capacity: '1,5 toneladas/dia',
    services: ['Coleta', 'Reciclagem', 'Recuperação'],
    serviceArea: 'Grande São Paulo',
    description: 'Empresa especializada em reciclagem de plástico pós-consumo e papelão industrial.',
    materialsAccepted: ['Plástico', 'Papelão', 'Metais ferrosos', 'Metais não-ferrosos'],
  },
  {
    id: 'op3',
    name: 'EcoTrat Resíduos e Reciclagem',
    type: 'Operador especializado',
    specialties: ['Resíduos contaminados', 'EPIs', 'Resíduos industriais'],
    rating: 4.9,
    distance: 22,
    capacity: '5 toneladas/dia',
    services: ['Coleta', 'Transporte', 'Tratamento', 'Destinação'],
    serviceArea: 'Região Metropolitana de São Paulo',
    description: 'Empresa licenciada (CETESB) para coleta, transporte e destinação de resíduos perigosos, contaminados e industriais.',
    materialsAccepted: ['Resíduos contaminados', 'EPIs usados', 'Resíduos industriais', 'Embalagens contaminadas', 'Lâmpadas', 'Resíduos perigosos'],
  },
  {
    id: 'op4',
    name: 'MetalRec Recuperação',
    type: 'Recuperadora de materiais',
    specialties: ['Metais', 'Sucata industrial'],
    rating: 4.7,
    distance: 18,
    capacity: '10 toneladas/dia',
    services: ['Coleta', 'Recuperação', 'Reciclagem'],
    serviceArea: 'ABC Paulista e São Paulo',
    description: 'Especializada na recuperação de metais ferrosos e não-ferrosos de origem industrial. Maior capacidade da região.',
    materialsAccepted: ['Aço carbono', 'Aço inox', 'Alumínio', 'Cobre', 'Sucata mista'],
  },
  {
    id: 'op5',
    name: 'TecnoCiclo',
    type: 'Recicladora especializada',
    specialties: ['Eletroeletrônicos', 'Cabos', 'Componentes'],
    rating: 4.8,
    distance: 25,
    capacity: '3 toneladas/dia',
    services: ['Coleta', 'Desmontagem', 'Recuperação'],
    serviceArea: 'São Paulo e Guarulhos',
    description: 'Referência em desmontagem e recuperação de equipamentos eletroeletrônicos e sucata eletrônica. Certificada e-Lixo.',
    materialsAccepted: ['Computadores', 'Cabos', 'Equipamentos eletrônicos', 'Componentes', 'Placas', 'Monitores'],
  },
];

export const INITIAL_REQUESTS: WasteRequest[] = [
  {
    id: 'req1',
    number: '001',
    wasteType: 'Papelão',
    wasteCategory: 'Recicláveis',
    quantity: 500,
    unit: 'kg',
    condition: 'Limpo',
    location: 'Av. Paulista, 1578 — São Paulo, SP',
    desiredDate: '15/09/2026',
    needsTransport: true,
    needsTreatment: 'Não',
    desiredDestination: 'Reciclagem',
    notes: 'Material prensado e separado por tipo. Disponível para coleta nas manhãs.',
    status: 'receiving_proposals',
    proposalCount: 3,
    createdAt: '10/09/2026',
  },
  {
    id: 'req2',
    number: '002',
    wasteType: 'EPIs contaminados',
    wasteCategory: 'EPIs',
    quantity: 150,
    unit: 'kg',
    condition: 'Contaminado',
    location: 'Av. Paulista, 1578 — São Paulo, SP',
    desiredDate: '18/09/2026',
    needsTransport: true,
    needsTreatment: 'Sim',
    desiredDestination: 'Tratamento',
    notes: 'EPIs utilizados em área contaminada. Necessita documentação de destinação adequada.',
    status: 'destination_confirmed',
    proposalCount: 2,
    selectedOperatorId: 'op3',
    createdAt: '08/09/2026',
  },
  {
    id: 'req3',
    number: '003',
    wasteType: 'Sucata metálica',
    wasteCategory: 'Resíduos industriais',
    quantity: 1200,
    unit: 'kg',
    condition: 'Separado',
    location: 'Av. Paulista, 1578 — São Paulo, SP',
    desiredDate: '20/09/2026',
    needsTransport: true,
    needsTreatment: 'Não',
    desiredDestination: 'Recuperação',
    notes: 'Sucata de aço carbono. Lote único disponível a partir de 20/09.',
    status: 'collection_scheduled',
    proposalCount: 2,
    selectedOperatorId: 'op4',
    createdAt: '09/09/2026',
  },
  {
    id: 'req4',
    number: '004',
    wasteType: 'Resíduos industriais',
    wasteCategory: 'Resíduos industriais',
    quantity: 800,
    unit: 'kg',
    condition: 'Misturado',
    location: 'Av. Paulista, 1578 — São Paulo, SP',
    desiredDate: '22/09/2026',
    needsTransport: true,
    needsTreatment: 'Não sei',
    desiredDestination: 'Avaliação do operador',
    notes: 'Resíduos industriais de processo. Aguardando avaliação técnica do operador.',
    status: 'receiving_proposals',
    proposalCount: 0,
    createdAt: '10/09/2026',
  },
  {
    id: 'req5',
    number: '005',
    wasteType: 'Lâmpadas fluorescentes',
    wasteCategory: 'Outros',
    quantity: 300,
    unit: 'unidades',
    condition: 'Necessita avaliação',
    location: 'Av. Paulista, 1578 — São Paulo, SP',
    desiredDate: '25/09/2026',
    needsTransport: true,
    needsTreatment: 'Sim',
    desiredDestination: 'Destinação adequada',
    notes: 'Lâmpadas de mercúrio e fluorescentes. Necessita embalagem adequada para transporte.',
    status: 'collection_scheduled',
    proposalCount: 1,
    selectedOperatorId: 'op3',
    createdAt: '10/09/2026',
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  { id: 'prop1', requestId: 'req1', operatorId: 'op1', value: 350, availableDate: '15/09/2026', availableTime: '08:00', services: ['Coleta', 'Triagem', 'Reciclagem'], notes: 'Material prensado facilita nosso processo. Emitimos certificado de destinação.', status: 'sent' },
  { id: 'prop2', requestId: 'req1', operatorId: 'op2', value: 320, availableDate: '15/09/2026', availableTime: '09:00', services: ['Coleta', 'Reciclagem', 'Recuperação'], notes: 'Temos parceria com papeleira local. Certificação completa após conclusão.', status: 'sent' },
  { id: 'prop3', requestId: 'req1', operatorId: 'op3', value: 850, availableDate: '16/09/2026', availableTime: '10:00', services: ['Coleta', 'Transporte', 'Destinação'], notes: 'Realizamos avaliação completa antes da destinação. MTR incluído.', status: 'sent' },
  { id: 'prop4', requestId: 'req2', operatorId: 'op3', value: 1200, availableDate: '18/09/2026', availableTime: '08:00', services: ['Coleta', 'Transporte', 'Tratamento', 'Destinação'], notes: 'Empresa licenciada para resíduos perigosos. MTR, manifesto e certificado inclusos.', status: 'accepted' },
  { id: 'prop5', requestId: 'req2', operatorId: 'op1', value: 0, availableDate: '20/09/2026', availableTime: '09:00', services: ['Coleta'], notes: 'Podemos coletar, mas o tratamento de EPIs contaminados não é nossa especialidade.', status: 'not_selected' },
  { id: 'prop6', requestId: 'req3', operatorId: 'op4', value: 480, availableDate: '20/09/2026', availableTime: '07:00', services: ['Coleta', 'Recuperação', 'Reciclagem'], notes: 'Especialistas em sucata ferrosa. Pagamos por tonelada acima de 1t. Caminhão disponível.', status: 'accepted' },
  { id: 'prop7', requestId: 'req3', operatorId: 'op2', value: 420, availableDate: '21/09/2026', availableTime: '08:00', services: ['Coleta', 'Reciclagem'], notes: 'Trabalhamos com sucata ferrosa e não-ferrosa.', status: 'not_selected' },
  { id: 'prop8', requestId: 'req5', operatorId: 'op3', value: 680, availableDate: '25/09/2026', availableTime: '09:00', services: ['Coleta', 'Transporte', 'Destinação'], notes: 'Licenciados para descarte de lâmpadas com mercúrio. Embalagem especial inclusa.', status: 'accepted' },
];

export const INITIAL_COLLECTIONS: Collection[] = [
  { id: 'col2', requestId: 'req2', operatorId: 'op3', scheduledDate: '18/09/2026', status: 'destination_confirmed' },
  { id: 'col3', requestId: 'req3', operatorId: 'op4', scheduledDate: '20/09/2026', status: 'scheduled' },
  { id: 'col5', requestId: 'req5', operatorId: 'op3', scheduledDate: '25/09/2026', status: 'scheduled' },
];

export const INITIAL_DESTINATIONS: Destination[] = [
  { id: 'dest2', collectionId: 'col2', destinationType: 'Tratamento e destinação final adequada', quantity: 148, date: '18/09/2026', notes: 'Material tratado conforme normativas ABNT. MTR #2026-EcoTrat-0892 emitido.' },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  { id: 'notif1', message: 'Nova proposta recebida', detail: 'Cooperativa Verde Vida enviou uma proposta para o Chamado #001.', type: 'proposal', requestId: 'req1', read: false, createdAt: '10/09/2026' },
  { id: 'notif2', message: 'Nova proposta recebida', detail: 'Novo Ciclo Reciclagem enviou uma proposta para o Chamado #001.', type: 'proposal', requestId: 'req1', read: false, createdAt: '10/09/2026' },
  { id: 'notif3', message: 'Coleta agendada', detail: 'A coleta do Chamado #003 está agendada para 20/09/2026.', type: 'schedule', requestId: 'req3', read: true, createdAt: '09/09/2026' },
  { id: 'notif4', message: 'Destinação confirmada', detail: 'EcoTrat Resíduos confirmou a destinação do Chamado #002.', type: 'destination', requestId: 'req2', read: true, createdAt: '10/09/2026' },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  { id: 'cert1', requestId: 'req2', collectionId: 'col2', validationCode: 'ECOXP-2026-002', createdAt: '18/09/2026' },
];

export const CO2E_FACTORS: Record<string, number> = {
  'Papelão': 0.4,
  'Papel': 0.4,
  'Plástico': 1.5,
  'Metal': 2.5,
  'Sucata metálica': 2.5,
  'Metais': 2.5,
  'Eletroeletrônicos': 3.0,
  'EPIs contaminados': 1.0,
  'EPIs': 1.0,
  'Resíduos industriais': 0.8,
  'Lâmpadas fluorescentes': 1.2,
  'Vidro': 0.3,
  'default': 0.8,
};

export function calcCo2e(wasteType: string, quantity: number): number {
  const factor = CO2E_FACTORS[wasteType] ?? CO2E_FACTORS['default'];
  return Math.round(quantity * factor);
}
